# Generated by Django 4.1.2 on 2022-10-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testAPI', '0002_alter_bucket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
